import Head from "next/head";
import styles from "../styles/Home.module.css";
import {
  Card,
  CardHeader,
  CardBody,
  Typography,
} from "@material-tailwind/react";

const Home = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Click Mints</title>
        <meta
          content="Generated by @rainbow-me/create-rainbowkit"
          name="description"
        />
        <link href="/favicon.ico" rel="icon" />
      </Head>

      <main className={styles.main}>
        <header className={styles.header_container}>
          <h1>
            Click <span>Mints</span>
          </h1>

          <p className="p-4 rounded-lg bg-gradient-to-r from-green-400 to-blue-500">
            Create, Mint and view your NFTs
          </p>
        </header>

        <div className={styles.grid}>
          <Card className="w-96 hover:border-4 border-rose-600">
            <CardHeader floated={false} className="h-60">
              <img src="/images/picture_nft.jpeg" alt="profile-picture" />
            </CardHeader>
            <CardBody className="text-center">
              <Typography variant="h4" color="blue-gray" className="mb-2">
                Gaming NFTs
              </Typography>
            </CardBody>
          </Card>

          <Card className="w-96 hover:border-4 border-rose-600">
            <CardHeader floated={false} className="h-60">
              <img src="/images/video_nfts.jpg" alt="profile-picture" />
            </CardHeader>
            <CardBody className="text-center">
              <Typography variant="h4" color="blue-gray" className="mb-2">
                Video NFTs
              </Typography>
            </CardBody>
          </Card>

          <Card className="w-96 hover:border-4 border-rose-600">
            <CardHeader floated={false} className="h-60">
              <img src="/images/music-nft.webp" alt="profile-picture" />
            </CardHeader>
            <CardBody className="text-center">
              <Typography variant="h4" color="blue-gray" className="mb-2">
                Music NFTs
              </Typography>
            </CardBody>
          </Card>

          <Card className="w-96 hover:border-4 border-rose-600">
            <CardHeader floated={false} className="h-60">
              <img src="/images/mystery_box.webp" alt="profile-picture" />
            </CardHeader>
            <CardBody className="text-center">
              <Typography variant="h4" color="blue-gray" className="mb-2">
                Mystery Box NFTs
              </Typography>
            </CardBody>
          </Card>

          <Card className="w-96 hover:border-4 border-rose-600">
            <CardHeader floated={false} className="h-60">
              <img src="/images/tickets.webp" alt="profile-picture" />
            </CardHeader>
            <CardBody className="text-center">
              <Typography variant="h4" color="blue-gray" className="mb-2">
                NFT Tickets
              </Typography>
            </CardBody>
          </Card>

          <Card className="w-96 hover:border-4 border-rose-600">
            <CardHeader floated={false} className="h-60">
              <img src="/images/badge.jpg" alt="profile-picture" />
            </CardHeader>
            <CardBody className="text-center">
              <Typography variant="h4" color="blue-gray" className="mb-2">
                OATs and POAPs
              </Typography>
            </CardBody>
          </Card>
        </div>
      </main>

      <footer className="flex w-full flex-row flex-wrap items-center justify-center gap-y-6 gap-x-12 border-t border-blue-gray-50 py-6 text-center md:justify-between">
        <Typography color="blue-gray" className="font-normal">
          &copy; 2023 web3masters inc. All rights reserved
        </Typography>
        <ul className="flex flex-wrap items-center gap-y-2 gap-x-8">
          <li>
            <Typography
              as="a"
              href="#"
              color="blue-gray"
              className="font-normal transition-colors hover:text-blue-500 focus:text-blue-500"
            >
              About Us
            </Typography>
          </li>
          <li>
            <Typography
              as="a"
              href="#"
              color="blue-gray"
              className="font-normal transition-colors hover:text-blue-500 focus:text-blue-500"
            >
              Join Us
            </Typography>
          </li>
          <li>
            <Typography
              as="a"
              href="#"
              color="blue-gray"
              className="font-normal transition-colors hover:text-blue-500 focus:text-blue-500"
            >
              Contribute
            </Typography>
          </li>
          <li>
            <Typography
              as="a"
              href="#"
              color="blue-gray"
              className="font-normal transition-colors hover:text-blue-500 focus:text-blue-500"
            >
              Contact Us
            </Typography>
          </li>
        </ul>
      </footer>
    </div>
  );
};

export default Home;
